name: update sigma folder

on:
  push:
    branches: [main]
    paths: "commonalities/**"

jobs:
  update-sigma:
    runs-on: ubuntu-latest
    steps:
      - name: checkout alpha
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ALPHA_TOKEN }}

      - name: push the changes to sigma
        run: |
          git fetch https://github.com/palaniappanodico/sigma.git main
          git merge --allow-unrelated-histories origin/main
          git pull --allow-unrelated-histories origin main
          git subtree push --prefix commonalities https://github.com/palaniappanodico/sigma.git main
