name: update sigma folder

on:
  push:
    branches: [main]
    paths: "legal/**"

jobs:
  update-sigma:
    runs-on: ubuntu-latest
    steps:
      - name: checkout alpha
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ALPHA_TOKEN }}

      - name: push the changes to delta
        run: |
          git subtree pull --prefix legal https://github.com/palaniappanodico/official.git main
          git subtree push --prefix legal https://github.com/palaniappanodico/official.git main
